### ISSUE TITLE
Supporting container scope

### ISSUE THREAD

**Issue by edgar-zigis** [akane/AnnotationInject#1]
Hello,
first of all, thank you for this great solution to decrease amount of the unnecessary boilerplate code (nice speech in the FrenchKit by the way). However, I still lack of one function: It seems, that the current macro script is dedicated only to **transient** scopes. I suggest supporting **container** scope too.

**Comment by pjechris** [comment]
Hi,

For now it only supports Swinject default scope which is `Graph`. This should do what you want when resolving ViewControllers. Did you have any issue about this?
But yeah supporting Swinject scopes would be a nice improvement.

**Comment by edgar-zigis** [comment]
I have updated request for now.

**Comment by pjechris** [comment]
@edgar-zigis I add the functionality, you can give it a go 👍

**Comment by edgar-zigis** [comment]
Amazing 👍
