### ISSUE TITLE
integrate AnnotationInject into project with SPM 

### ISSUE THREAD

**Issue by dhemaiedrihab1** [akane/AnnotationInject#19]
Hello,

We were using your library via Cocoapods but now we're migrating our application to SPM.

we're actually using the version forked from your project, https://github.com/david-spaeth/AnnotationInject and to add it to our Package Dependencies we applied some modifications to upgrade the versions of the dependencies you're using, you can find it in the branch brc-swift-inject-spm !! 

Then, after adding the Package to our project via "Add Package Dependencies", adding the Build Phases run script "swift run annotationinject-cli --sources <path to your sources> --output <path to output generated code> (--args imports=<MyLib1> -args imports=<MyLib2>>)" we had an error saying "Could not find Package.swift in this directory or any of its parent directories"

So, Is it not possible to add it via "Add Package Dependencies" but we should create a Package.swift file then add it via the file ? 

Thank you in advance.
Cordially.

**Comment by pjechris** [comment]
Hello

Unfortunately Xcode manages SPM differently than when having Package.swift. So you can't run `swift run` 😬 .

However there might be some workarounds. Turned out I had to do it a few days ago with Apollo ^^.

Could you try this and let me know if it worked :
```swift
SPM_CHECKOUT_DIR=${BUILD_DIR%Build/*}SourcePackages/checkouts

cd $SPM_CHECKOUT_DIR
swift run annotationinject-cli --sources --output
```

**Comment by dhemaiedrihab1** [comment]
Hello, 

Thank you for your answer :) 

After trying that I had this problem :

<img width="566" alt="Capture d’écran 2024-02-08 à 16 03 25" src="https://github.com/pjechris/AnnotationInject/assets/105491925/41618388-8d79-47ae-ac5b-960ba638c48e">

**Comment by pjechris** [comment]
Sorry I was not clear but this is the script you have to run for Xcode inside a Build phase.

If you want to test it in a shell (and only for this), you'll first have to grab `BUILD_DIR` value from Xcode and set it into your shell (you can see the value in Xcode build logs inside Build phases).

If you intend to manage dependencies through Xcode but run command through shell I'm not sure it's possible. Unless if you find a way to find `BUILD_DIR` value using `xcodebuild`.

<img width="1459" alt="Screenshot 2024-02-08 at 17 11 10" src="https://github.com/pjechris/AnnotationInject/assets/7334856/8d5aca57-f4e3-438f-af71-269cf063dacb">

```shell
shell > BUILD_DIR=...
shell > SPM_CHECKOUT_DIR=${BUILD_DIR%Build/*}SourcePackages/checkouts
shell > cd $SPM_CHECKOUT_DIR
shell > swift run annotationinject-cli --sources --output
```

**Comment by dhemaiedrihab1** [comment]
Thanks for the clarification . 

So now, I tried both ways ! adding the script into Build Phase and via shell and I had the same problem "Could not find Package.swift in this directory or any of its parent directories."

with shell: 

<img width="772" alt="Capture d’écran 2024-02-08 à 17 44 07" src="https://github.com/pjechris/AnnotationInject/assets/105491925/2c27776c-571b-4a7c-b860-d5cbfa7ee98c">


with Run Script: 

<img width="785" alt="Capture d’écran 2024-02-08 à 17 50 40" src="https://github.com/pjechris/AnnotationInject/assets/105491925/feaf82e7-dafc-4cec-8481-8f8dedf50fea">

<img width="544" alt="Capture d’écran 2024-02-08 à 17 50 26" src="https://github.com/pjechris/AnnotationInject/assets/105491925/7545c601-1520-4bb8-a382-dbce0e7a8aac">

**Comment by pjechris** [comment]
I tried on my side. Unfortunately seems like Xcode doesn't pull dependencies when it's not used inside the app. So this won't work :(

So for now the only way of using AnnotationInject with SPM is indeed with `Package.swift`. Sorry.

Adding support for plugin might allow to use it right from Xcode but would need to have a look.

**Comment by dhemaiedrihab1** [comment]
Ok thanks for your feedback.

We'll see how to try to solve this on our side ! 

And do you think you'll be able to look at this soon and come with a solution ?

**Comment by david-spaeth** [comment]
Hey there,

Just wanted to drop a quick note to say everything's up and running smoothly now. Here's the updated script:

```

SPM_CHECKOUT_DIR=${BUILD_DIR%Build/*}SourcePackages/checkouts/AnnotationInject
cd $SPM_CHECKOUT_DIR
/usr/bin/xcrun --sdk macosx swift run annotationinject-cli ...

```

Big thanks to @pjechris for pointing me in the right direction.

Feel free to consider adding this to the README for future reference. It could really come in handy for others.  Cheers!

**Comment by pjechris** [comment]
That should definitely help some people so I'll add it to README.

Thank you :)
