### ISSUE TITLE
found nil in ServiceResolver extension

### ISSUE THREAD

**Issue by MuhammadEhsanMirzaei** [akane/AnnotationInject#9]
Unexpectedly found nil while unwrapping an Optional value in ServiceResolver extension
![Screen Shot 2019-08-14 at 11 39 03 AM](https://user-images.githubusercontent.com/29886464/63001140-2a899480-be88-11e9-831e-a1e969e2d59a.png)
finished with error - code: -1001
Swinject: Resolution failed. Expected registration:
	{ Service: TrainListRouter, Factory: Resolver -> TrainListRouter }

**Comment by MohammadEhsanMirzaaee** [comment]
finished with error - code: -1001
Swinject: Resolution failed. Expected registration:
	{ Service: TrainListRouter, Factory: Resolver -> TrainListRouter }

**Comment by pjechris** [comment]
Hi @MohammadEhsanMirzaaee

Could you tell me which version of AnnotationInject you're using? There was a known bug in 0.3.0 which was resolved into 0.3.1.
Also, what do you have into `Register.generated.swift` for `TrainListRouter` and/or `TrainListRouterProtocol`?

**Comment by MohammadEhsanMirzaaee** [comment]
Hi
version: AnnotationInject (0.3.3)
Register.generated.swift:
`import Swinject

class AnnotationAssembly: Assembly {
  func assemble(container: Container) {
  container.register(TrainListRouterProtocol.self) { resolver in
      return TrainListRouter()
  }
  .initCompleted { resolver, service in
  }
  .inObjectScope(.graph)

  container.register(TrainSearchViewController.self) { resolver in
      return TrainSearchViewController()
  }
  .initCompleted { resolver, service in
        service.trainListRouter = resolver.registeredService()
  }
  }
}
`

TrainListRouter Class:
`// sourcery:inject
final class TrainListRouter
{
    private let storyboard = UIStoryboard(name: "TrainList", bundle: nil)
}

/// sourcery:inject: scope = "graph", type = "TrainListRouterProtocol"
extension TrainListRouter: TrainListRouterProtocol
{
    func createModule(userSearchModel: UserTrainSearchModel) -> TrainListViewController
    {
        ...some code
    }
}
`

I want use dependency injection in below 
`// sourcery: inject
class TrainSearchViewController: BaseController
{
 
    /// sourcery: inject
    public var trainListRouter: TrainListRouterProtocol!`

**Comment by MuhammadEhsanMirzaei** [comment]
Hi
version: AnnotationInject (0.3.3)
Register.generated.swift:
<img width="534" alt="Screen Shot 2019-08-16 at 12 25 36 PM" src="https://user-images.githubusercontent.com/29886464/63154563-27c4a600-c026-11e9-91ef-ce741d8cb430.png">

and my TrainListRouter Class:
<img width="1175" alt="Screen Shot 2019-08-16 at 1 01 17 PM" src="https://user-images.githubusercontent.com/29886464/63154600-3b700c80-c026-11e9-924c-2677d05d062d.png">
 
I want to use dependecy injection in below controller:
<img width="493" alt="Screen Shot 2019-08-16 at 1 02 39 PM" src="https://user-images.githubusercontent.com/29886464/63154639-504ca000-c026-11e9-8008-f6b9969bec8a.png">

**Comment by pjechris** [comment]
I've just released a 0.4.1 on Cocoapods that should fix your issue.

**Comment by MuhammadEhsanMirzaei** [comment]
thanks, can you provide a sample? need to a sample is felt, [sample like this](https://github.com/SpectralDragon/Viper-LightRoute-Swinject/blob/master/ViperMCFSwift/Modules/FisrtModule/Configurator/FisrtModuleAssemblyContainer.swift)

and multiple "sourcery: inject" for one class with two interface

**Comment by pjechris** [comment]
I'm sorry what do you want a sample for? Code from your previous screenshot should work now.

As for multiple injection for one class I think providers would achieve what you're looking for:
```swift
/// sourcery: provider
class MyFactory {
 static func instantiate(resolver: ServiceResolver) -> ProtocolA {
     return TrainListRouter()
 }

  static func instantiate(resolver: ServiceResolver) -> ProtocolB {
     return TrainListRouter()
  }
}
```
I never tested them with attributes injections so you might hit a framework corner.

**Comment by MuhammadEhsanMirzaei** [comment]
after release 0.4.1 I get this error in build time: 
`Error Domain=NSCocoaErrorDomain Code=260 "The file “InjectAnnotation.swift” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Volumes/Untitled/Projects/TestProjects/AnnotationInjectTest/Pods/AnnotationInject/Scripts/../Templates/../Sources/InjectAnnotation.swift, NSUnderlyingError=0x7fca36ca5710 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`
this part is wrong: "../Templates/../Sources"

**Comment by pjechris** [comment]
Thanks for the notification. Unfortunately it will take some times to fix as it appear than using Soucery source code with Cocoapods is not compatible.

In the meantime, you can use `pod "AnnotationInject", :git => "https://github.com/david-spaeth/AnnotationInject", :branch => "brc-inject"`

**Comment by pjechris** [comment]
@MohammadEhsanMirzaaee You can try with 0.4.2

**Comment by pjechris** [comment]
@MohammadEhsanMirzaaee Is it working with latest version?

**Comment by MuhammadEhsanMirzaei** [comment]
sorry, I used another library
